include:
  - project: cloud_arv/health-tech/partner-solution/pipelines
    ref: main
    file:
      - nextjs-pipeline.yml
      - deployments/partner-solution.yml

variables:
  APPLICATION_NAME: playground-dashboard
  PROJECT_NAME: partner-solution