const FONT_PRIMARY_REGULAR = 'NotoSansThai-Regular, sans-serif';
const FONT_PRIMARY_SEMIBOLD = 'NotoSansThai-SemiBold, sans-serif';
const FONT_PRIMARY_MEDIUM = 'NotoSansThai-Medium, sans-serif';

export const typography = {
  fontFamily: FONT_PRIMARY_REGULAR,
  fontWeightRegular: 400,
  fontWeightMedium: 500,
  fontWeightSemiBold: 600,

  displayLargeSemiBold: {
    fontWeight: 500,
    letterSpacing: -0.25,
    lineHeight: '64px',
    fontSize: 57,
    fontFamily: FONT_PRIMARY_SEMIBOLD,
  },
  displayLarge: {
    fontWeight: 400,
    letterSpacing: -0.25,
    lineHeight: '64px',
    fontSize: 57,
    fontFamily: FONT_PRIMARY_REGULAR,
  },
  displayMediumSemiBold: {
    fontWeight: 500,
    letterSpacing: 0,
    lineHeight: '52px',
    fontSize: 45,
    fontFamily: FONT_PRIMARY_SEMIBOLD,
  },
  displayMedium: {
    fontWeight: 400,
    letterSpacing: 0,
    lineHeight: '52px',
    fontSize: 45,
    fontFamily: FONT_PRIMARY_REGULAR,
  },
  displaySmallSemiBold: {
    fontWeight: 500,
    letterSpacing: 0,
    lineHeight: '44px',
    fontSize: 36,
    fontFamily: FONT_PRIMARY_SEMIBOLD,
  },
  displaySmall: {
    fontWeight: 400,
    letterSpacing: 0,
    lineHeight: '44px',
    fontSize: 36,
    fontFamily: FONT_PRIMARY_REGULAR,
  },
  headlineLargeSemiBold: {
    fontWeight: 500,
    letterSpacing: 0,
    lineHeight: '40px',
    fontSize: 32,
    fontFamily: FONT_PRIMARY_SEMIBOLD,
  },
  headlineLarge: {
    fontWeight: 400,
    letterSpacing: 0,
    lineHeight: '40px',
    fontSize: 32,
    fontFamily: FONT_PRIMARY_REGULAR,
  },
  headlineMediumSemiBold: {
    fontWeight: 500,
    lineHeight: '36px',
    letterSpacing: 0,
    fontSize: 28,
    fontFamily: FONT_PRIMARY_SEMIBOLD,
  },
  headlineMediumBold: {
    fontWeight: 600,
    lineHeight: '36px',
    letterSpacing: 0,
    fontSize: 28,
    fontFamily: FONT_PRIMARY_SEMIBOLD,
  },
  headlineMedium: {
    fontWeight: 400,
    lineHeight: '36px',
    letterSpacing: 0,
    fontSize: 28,
    fontFamily: FONT_PRIMARY_REGULAR,
  },
  headlineSmallSemiBold: {
    fontWeight: 500,
    lineHeight: '32px',
    letterSpacing: 0,
    fontSize: 24,
    fontFamily: FONT_PRIMARY_SEMIBOLD,
    // ...responsiveFontSizes({ sm: 19, md: 20, lg: 20 }),
  },
  headlineSmall: {
    fontWeight: 400,
    letterSpacing: 0,
    lineHeight: '32px',
    fontSize: 24,
    fontFamily: FONT_PRIMARY_REGULAR,
  },
  titleLargeSemiBold: {
    fontWeight: 500,
    lineHeight: '28px',
    letterSpacing: 0,
    fontSize: 20,
    fontFamily: FONT_PRIMARY_SEMIBOLD,
  },
  titleLargeBold: {
    fontWeight: 600,
    lineHeight: '28px',
    letterSpacing: 0,
    fontSize: 20,
    fontFamily: FONT_PRIMARY_SEMIBOLD,
  },
  titleLarge: {
    fontWeight: 400,
    lineHeight: '28px',
    letterSpacing: 0,
    fontSize: 20,
    fontFamily: FONT_PRIMARY_REGULAR,
  },
  titleMediumBold: {
    fontWeight: 600,
    lineHeight: '24px',
    letterSpacing: 0.15,
    fontSize: 16,
    fontFamily: FONT_PRIMARY_SEMIBOLD,
  },
  titleMediumSemiBold: {
    fontWeight: 500,
    lineHeight: '24px',
    letterSpacing: 0.15,
    fontSize: 16,
    fontFamily: FONT_PRIMARY_SEMIBOLD,
  },
  titleMedium: {
    fontWeight: 500,
    lineHeight: '24px',
    letterSpacing: 0.15,
    fontSize: 16,
    fontFamily: FONT_PRIMARY_MEDIUM,
  },
  titleSmallSemiBold: {
    fontWeight: 500,
    lineHeight: '20px',
    letterSpacing: 0.1,
    fontSize: 14,
    fontFamily: FONT_PRIMARY_SEMIBOLD,
  },
  titleSmall: {
    fontWeight: 500,
    lineHeight: '20px',
    letterSpacing: 0.1,
    fontSize: 14,
    fontFamily: FONT_PRIMARY_MEDIUM,
  },
  bodyLargeSemiBold: {
    fontWeight: 500,
    lineHeight: '24px',
    letterSpacing: 0.5,
    fontSize: 16,
    fontFamily: FONT_PRIMARY_SEMIBOLD,
  },
  bodyLarge: {
    fontWeight: 400,
    lineHeight: '24px',
    letterSpacing: 0.5,
    fontSize: 16,
    fontFamily: FONT_PRIMARY_REGULAR,
  },
  bodyMediumSemiBold: {
    fontWeight: 500,
    lineHeight: '20px',
    letterSpacing: 0.25,
    fontSize: 14,
    fontFamily: FONT_PRIMARY_SEMIBOLD,
  },
  bodyMedium: {
    fontWeight: 400,
    lineHeight: '20px',
    letterSpacing: 0.25,
    fontSize: 14,
    fontFamily: FONT_PRIMARY_REGULAR,
  },
  bodySmallSemiBold: {
    fontWeight: 500,
    lineHeight: '16px',
    letterSpacing: 0.4,
    fontSize: 12,
    fontFamily: FONT_PRIMARY_SEMIBOLD,
  },
  bodySmall: {
    fontWeight: 400,
    lineHeight: '16px',
    letterSpacing: 0.4,
    fontSize: 12,
    fontFamily: FONT_PRIMARY_REGULAR,
  },
  labelExtraLargeSemiBold: {
    fontWeight: 500,
    lineHeight: '24px',
    letterSpacing: 0.1,
    fontSize: 16,
    fontFamily: FONT_PRIMARY_SEMIBOLD,
  },
  labelExtraLarge: {
    fontWeight: 500,
    lineHeight: '24px',
    letterSpacing: 0.1,
    fontSize: 16,
    fontFamily: FONT_PRIMARY_MEDIUM,
  },
  labelLargeBold: {
    fontWeight: 600,
    lineHeight: '20px',
    letterSpacing: 0.1,
    fontSize: 14,
    fontFamily: FONT_PRIMARY_SEMIBOLD,
  },
  labelLargeSemiBold: {
    fontWeight: 500,
    lineHeight: '20px',
    letterSpacing: 0.1,
    fontSize: 14,
    fontFamily: FONT_PRIMARY_SEMIBOLD,
  },
  labelLarge: {
    fontWeight: 400,
    lineHeight: '20px',
    letterSpacing: 0.1,
    fontSize: 14,
    fontFamily: FONT_PRIMARY_MEDIUM,
  },
  labelMediumSemiBold: {
    fontWeight: 500,
    lineHeight: '16px',
    letterSpacing: 0.5,
    fontSize: 12,
    fontFamily: FONT_PRIMARY_SEMIBOLD,
  },
  labelMedium: {
    fontWeight: 500,
    lineHeight: '16px',
    letterSpacing: 0.5,
    fontSize: 12,
    fontFamily: FONT_PRIMARY_MEDIUM,
  },
  labelSmallSemiBold: {
    fontWeight: 500,
    lineHeight: '16px',
    letterSpacing: 0.5,
    fontSize: 11,
    fontFamily: FONT_PRIMARY_SEMIBOLD,
  },
  labelSmall: {
    fontWeight: 500,
    lineHeight: '16px',
    letterSpacing: 0.5,
    fontSize: 11,
    fontFamily: FONT_PRIMARY_MEDIUM,
  },
};

export const TypographyMapping = {
  MuiTypography: {
    defaultProps: {
      variantMapping: {
        displayLargeSemiBold: 'h1',
        displayLarge: 'h1',
        displayMediumSemiBold: 'h1',
        displayMedium: 'h1',
        displaySmallSemiBold: 'h1',
        displaySmall: 'h1',
        headlineLargeSemiBold: 'h2',
        headlineLarge: 'h2',
        headlineMediumBold: 'h2',
        headlineMediumSemiBold: 'h2',
        headlineMedium: 'h2',
        headlineSmallSemiBold: 'h2',
        headlineSmall: 'h2',
        titleLargeBold: 'h3',
        titleLargeSemiBold: 'h3',
        titleLarge: 'h3',
        titleMediumBold: 'h3',
        titleMediumSemiBold: 'h3',
        titleMedium: 'h3',
        titleSmallSemiBold: 'h3',
        titleSmall: 'h3',
        bodyLargeSemiBold: 'span',
        bodyLarge: 'span',
        bodyMediumSemiBold: 'span',
        bodyMedium: 'span',
        bodySmallSemiBold: 'span',
        bodySmall: 'span',
        labelExtraLargeSemiBold: 'span',
        labelExtraLarge: 'span',
        labelLargeBold: 'span',
        labelLargeSemiBold: 'span',
        labelLarge: 'span',
        labelMediumSemiBold: 'span',
        labelMedium: 'span',
        labelSmallSemiBold: 'span',
        labelSmall: 'span',
      },
    },
  },
};
