export { default as IconHomePage } from './icons/icon-home-page.svg'
export { default as IconHomePageActive } from './icons/icon-home-page-active.svg'
export { default as IconLogout } from './icons/icon-logout.svg'
export { default as IconMenuItem } from './icons/icon-menu-item.svg'
export { default as IconMenuItemActive } from './icons/icon-menu-item-active.svg'
export { default as IconNotification } from './icons/icon-notification.svg'
export { default as IconSetting } from './icons/icon-setting.svg'
export { default as IconSparkle } from './icons/icon-sparkle.svg'
export { default as IconCreditCoin } from './icons/icon-credit-coin.svg'
export { default as IconPerson } from './icons/icon-person.svg'

export { default as ImageCoverBg } from './images/image-cover-bg.jpg'
export { default as ImageCarivaLogo } from './images/cariva-logo.svg'
export { default as ImagePlaygrondLogo } from './images/playground-logo.svg'
export { default as ImagePlaygrondLogoColor } from './images/playground-logo-color.svg'
export { default as ImagePlaygroudLogoOverlay } from './images/playground-logo-overlay.svg'
export { default as ImageLoadingStack } from './images/loading-stack.gif'

